version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ledger_db
    environment:
      POSTGRES_USER: ledger_admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: ledger_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
